### ISSUE TITLE
Train Topics Missing

### ISSUE THREAD

**Issue by ToluClassics** [hltcoe/HC4#4]
Hi @eugene-yang, @dlawrie 

I noticed that some of the train human translation topics are empty

e.g Farsi topic_id 1027 is blank,  all the Russian human translations are missing too
I am looking at this file: https://github.com/hltcoe/HC4/blob/main/resources/hc4/train.topics.v1-0.jsonl

Kindly assist, Thanks!

**Comment by dlawrie** [comment]
We did not produce human translations for all train topics. Also those topics maybe incompletely judged.

**Comment by ToluClassics** [comment]
Thanks for the info!
